name: create issue

on:
  schedule:
    - cron: "0 1 * * 3"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v1
      - name: Use Node.js lts
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm i
      - uses: actions/github-script@v6
        with:
          script: |
            const { createIssue } = await import('${{ github.workspace }}/ci.js')

            await createIssue({github, context});
      - name: push main
        run: |
          git add .
          git commit -m 'update issue'
          git push origin main
